In [1]:
import pandas as pd
import numpy as np
pd.options.display.max_rows = None
pd.options.display.max_columns = None
df = pd.read_csv("domestic-stu.txt",sep=",")
df

      FirstName    LastName Province  CGPA  ResearchScore
0          Mary       White       BC  4.00             85
1          Mike       Hwang       ON  3.70             90
2          Liam     Edwards       AB  4.33             70
3          Noah     Collins       BC  4.20             71
4       William     Stewart       MB  4.10             72
5         James     Sanchez       NB  4.00             73
6        Oliver      Morris       NL  3.90             74
7      Benjamin      Rogers       NT  3.80             75
8        Elijah        Reed       NS  3.70             76
9         Lucas        Cook       NU  3.60             77
10        Mason      Morgan       ON  3.50             78
11        Logan        Bell       PE  3.40             79
12    Alexander      Murphy       QC  3.30             80
13        Ethan      Bailey       SK  3.20             81
14        Jacob      Rivera       YT  3.10             82
15      Michael      Cooper       AB  3.00             83
16       Daniel  Richardson       BC  2.90             84
17        Henry         Cox       MB  2.80             85
18      Jackson      Howard       NB  4.25             86
19    Sebastian        Ward       NL  4.15             87
20        Aiden      Torres       NT  4.05             88
21      Matthew    Peterson       NS  3.95             89
22       Samuel        Gray       NU  3.85             90
23        David     Ramirez       ON  3.75             91
24       Joseph       James       PE  3.65             92
25       Carter      Watson       QC  3.55             93
26         Owen      Brooks       SK  3.45             94
27        Wyatt       Kelly       YT  3.35             95
28         John     Sanders       AB  3.25             96
29         Jack       Price       BC  3.15             97
30         Luke     Bennett       MB  3.05             98
31       Jayden        Wood       NB  2.95             99
32        Dylan      Barnes       NL  2.85            100
33      Grayson        Ross       NT  4.33             99
34         Levi   Henderson       NS  4.20             98
35        Isaac     Coleman       NU  4.10             97
36      Gabriel     Jenkins       ON  4.00             96
37       Julian       Perry       PE  3.90             95
38        Mateo      Powell       QC  3.80             94
39      Anthony        Long       SK  3.70             93
40        Jaxon   Patterson       YT  3.60             92
41      Lincoln      Hughes       AB  3.50             91
42       Joshua      Flores       BC  3.40             90
43  Christopher  Washington       MB  3.30             89
44       Andrew      Butler       NB  3.20             88
45     Theodore     Simmons       NL  3.10             87
46        Caleb      Foster       NT  3.00             86
47         Ryan    Gonzales       NS  2.90             85
48        Asher      Bryant       NU  2.80             84
49       Nathan   Alexander       ON  4.25             83
50       Thomas     Russell       PE  4.15             82
51         Emma     Griffin       QC  4.05             81
52       Olivia     Stewart       SK  3.95             80
53          Ava     Sanchez       YT  3.85             79
54     Isabella      Morris       AB  3.75             78
55       Sophia      Rogers       BC  3.65             77
56    Charlotte        Reed       MB  3.55             76
57          Mia        Cook       NB  3.45             75
58       Amelia      Morgan       NL  3.35             74
59       Harper        Bell       NT  3.25             73
60       Evelyn      Murphy       NS  3.15             72
61      Abigail      Bailey       NU  3.05             71
62        Emily      Rivera       ON  2.95             70
63    Elizabeth      Cooper       PE  2.85            100
64         Mila  Richardson       QC  4.33             99
65         Ella         Cox       SK  4.20             98
66        Avery      Howard       YT  4.10             97
67        Sofia        Ward       AB  4.00             96
68       Camila      Torres       BC  3.90             95
69         Aria    Peterson       MB  3.80             94
70     Scarlett        Gray       NB  3.70             93
71     Victoria     Ramirez       NL  3.60             92
72      Madison       James       NT  3.50             91
73         Luna      Watson       NS  3.40             90
74        Grace      Brooks       NU  3.30             89
75        Chloe       Kelly       ON  3.20             88
76     Penelope     Sanders       PE  3.10             87
77        Layla       Price       QC  3.00             86
78        Riley     Bennett       SK  2.90             85
79         Zoey        Wood       YT  2.80             84
80         Nora      Barnes       AB  4.25             83
81         Lily        Ross       BC  4.15             82
82      Eleanor   Henderson       MB  4.05             81
83       Hannah     Coleman       NB  3.95             80
84      Lillian     Jenkins       NL  3.85             79
85      Addison       Perry       NT  3.75             78
86       Aubrey      Powell       NS  3.65             77
87        Ellie        Long       NU  3.55             76
88       Stella   Patterson       ON  3.45             75
89      Natalie      Hughes       PE  3.35             74
90          Zoe      Flores       QC  3.25             73
91         Leah  Washington       SK  3.15             72
92        Hazel      Butler       YT  3.05             71
93       Violet     Simmons       AB  2.95             70
94       Aurora      Foster       BC  2.85            100
95     Savannah    Gonzales       MB  3.85             99
96       Audrey      Bryant       NB  3.75             98
97     Brooklyn   Alexander       NL  3.65             97
98        Bella     Russell       NT  3.55             96
99       Claire     Griffin       NS  3.45             95

In [2]:
df["LastName"].replace({"Rogers":"David", "Morris":"Tomas"},inplace=True)

In [3]:
df["Province"]= df["Province"].str.lower()
df

      FirstName    LastName Province  CGPA  ResearchScore
0          Mary       White       bc  4.00             85
1          Mike       Hwang       on  3.70             90
2          Liam     Edwards       ab  4.33             70
3          Noah     Collins       bc  4.20             71
4       William     Stewart       mb  4.10             72
5         James     Sanchez       nb  4.00             73
6        Oliver       Tomas       nl  3.90             74
7      Benjamin       David       nt  3.80             75
8        Elijah        Reed       ns  3.70             76
9         Lucas        Cook       nu  3.60             77
10        Mason      Morgan       on  3.50             78
11        Logan        Bell       pe  3.40             79
12    Alexander      Murphy       qc  3.30             80
13        Ethan      Bailey       sk  3.20             81
14        Jacob      Rivera       yt  3.10             82
15      Michael      Cooper       ab  3.00             83
16       Daniel  Richardson       bc  2.90             84
17        Henry         Cox       mb  2.80             85
18      Jackson      Howard       nb  4.25             86
19    Sebastian        Ward       nl  4.15             87
20        Aiden      Torres       nt  4.05             88
21      Matthew    Peterson       ns  3.95             89
22       Samuel        Gray       nu  3.85             90
23        David     Ramirez       on  3.75             91
24       Joseph       James       pe  3.65             92
25       Carter      Watson       qc  3.55             93
26         Owen      Brooks       sk  3.45             94
27        Wyatt       Kelly       yt  3.35             95
28         John     Sanders       ab  3.25             96
29         Jack       Price       bc  3.15             97
30         Luke     Bennett       mb  3.05             98
31       Jayden        Wood       nb  2.95             99
32        Dylan      Barnes       nl  2.85            100
33      Grayson        Ross       nt  4.33             99
34         Levi   Henderson       ns  4.20             98
35        Isaac     Coleman       nu  4.10             97
36      Gabriel     Jenkins       on  4.00             96
37       Julian       Perry       pe  3.90             95
38        Mateo      Powell       qc  3.80             94
39      Anthony        Long       sk  3.70             93
40        Jaxon   Patterson       yt  3.60             92
41      Lincoln      Hughes       ab  3.50             91
42       Joshua      Flores       bc  3.40             90
43  Christopher  Washington       mb  3.30             89
44       Andrew      Butler       nb  3.20             88
45     Theodore     Simmons       nl  3.10             87
46        Caleb      Foster       nt  3.00             86
47         Ryan    Gonzales       ns  2.90             85
48        Asher      Bryant       nu  2.80             84
49       Nathan   Alexander       on  4.25             83
50       Thomas     Russell       pe  4.15             82
51         Emma     Griffin       qc  4.05             81
52       Olivia     Stewart       sk  3.95             80
53          Ava     Sanchez       yt  3.85             79
54     Isabella       Tomas       ab  3.75             78
55       Sophia       David       bc  3.65             77
56    Charlotte        Reed       mb  3.55             76
57          Mia        Cook       nb  3.45             75
58       Amelia      Morgan       nl  3.35             74
59       Harper        Bell       nt  3.25             73
60       Evelyn      Murphy       ns  3.15             72
61      Abigail      Bailey       nu  3.05             71
62        Emily      Rivera       on  2.95             70
63    Elizabeth      Cooper       pe  2.85            100
64         Mila  Richardson       qc  4.33             99
65         Ella         Cox       sk  4.20             98
66        Avery      Howard       yt  4.10             97
67        Sofia        Ward       ab  4.00             96
68       Camila      Torres       bc  3.90             95
69         Aria    Peterson       mb  3.80             94
70     Scarlett        Gray       nb  3.70             93
71     Victoria     Ramirez       nl  3.60             92
72      Madison       James       nt  3.50             91
73         Luna      Watson       ns  3.40             90
74        Grace      Brooks       nu  3.30             89
75        Chloe       Kelly       on  3.20             88
76     Penelope     Sanders       pe  3.10             87
77        Layla       Price       qc  3.00             86
78        Riley     Bennett       sk  2.90             85
79         Zoey        Wood       yt  2.80             84
80         Nora      Barnes       ab  4.25             83
81         Lily        Ross       bc  4.15             82
82      Eleanor   Henderson       mb  4.05             81
83       Hannah     Coleman       nb  3.95             80
84      Lillian     Jenkins       nl  3.85             79
85      Addison       Perry       nt  3.75             78
86       Aubrey      Powell       ns  3.65             77
87        Ellie        Long       nu  3.55             76
88       Stella   Patterson       on  3.45             75
89      Natalie      Hughes       pe  3.35             74
90          Zoe      Flores       qc  3.25             73
91         Leah  Washington       sk  3.15             72
92        Hazel      Butler       yt  3.05             71
93       Violet     Simmons       ab  2.95             70
94       Aurora      Foster       bc  2.85            100
95     Savannah    Gonzales       mb  3.85             99
96       Audrey      Bryant       nb  3.75             98
97     Brooklyn   Alexander       nl  3.65             97
98        Bella     Russell       nt  3.55             96
99       Claire     Griffin       ns  3.45             95

In [4]:
df["LastName"]="Ph.d" + df["LastName"] 
df

      FirstName        LastName Province  CGPA  ResearchScore
0          Mary       Ph.dWhite       bc  4.00             85
1          Mike       Ph.dHwang       on  3.70             90
2          Liam     Ph.dEdwards       ab  4.33             70
3          Noah     Ph.dCollins       bc  4.20             71
4       William     Ph.dStewart       mb  4.10             72
5         James     Ph.dSanchez       nb  4.00             73
6        Oliver       Ph.dTomas       nl  3.90             74
7      Benjamin       Ph.dDavid       nt  3.80             75
8        Elijah        Ph.dReed       ns  3.70             76
9         Lucas        Ph.dCook       nu  3.60             77
10        Mason      Ph.dMorgan       on  3.50             78
11        Logan        Ph.dBell       pe  3.40             79
12    Alexander      Ph.dMurphy       qc  3.30             80
13        Ethan      Ph.dBailey       sk  3.20             81
14        Jacob      Ph.dRivera       yt  3.10             82
15      Michael      Ph.dCooper       ab  3.00             83
16       Daniel  Ph.dRichardson       bc  2.90             84
17        Henry         Ph.dCox       mb  2.80             85
18      Jackson      Ph.dHoward       nb  4.25             86
19    Sebastian        Ph.dWard       nl  4.15             87
20        Aiden      Ph.dTorres       nt  4.05             88
21      Matthew    Ph.dPeterson       ns  3.95             89
22       Samuel        Ph.dGray       nu  3.85             90
23        David     Ph.dRamirez       on  3.75             91
24       Joseph       Ph.dJames       pe  3.65             92
25       Carter      Ph.dWatson       qc  3.55             93
26         Owen      Ph.dBrooks       sk  3.45             94
27        Wyatt       Ph.dKelly       yt  3.35             95
28         John     Ph.dSanders       ab  3.25             96
29         Jack       Ph.dPrice       bc  3.15             97
30         Luke     Ph.dBennett       mb  3.05             98
31       Jayden        Ph.dWood       nb  2.95             99
32        Dylan      Ph.dBarnes       nl  2.85            100
33      Grayson        Ph.dRoss       nt  4.33             99
34         Levi   Ph.dHenderson       ns  4.20             98
35        Isaac     Ph.dColeman       nu  4.10             97
36      Gabriel     Ph.dJenkins       on  4.00             96
37       Julian       Ph.dPerry       pe  3.90             95
38        Mateo      Ph.dPowell       qc  3.80             94
39      Anthony        Ph.dLong       sk  3.70             93
40        Jaxon   Ph.dPatterson       yt  3.60             92
41      Lincoln      Ph.dHughes       ab  3.50             91
42       Joshua      Ph.dFlores       bc  3.40             90
43  Christopher  Ph.dWashington       mb  3.30             89
44       Andrew      Ph.dButler       nb  3.20             88
45     Theodore     Ph.dSimmons       nl  3.10             87
46        Caleb      Ph.dFoster       nt  3.00             86
47         Ryan    Ph.dGonzales       ns  2.90             85
48        Asher      Ph.dBryant       nu  2.80             84
49       Nathan   Ph.dAlexander       on  4.25             83
50       Thomas     Ph.dRussell       pe  4.15             82
51         Emma     Ph.dGriffin       qc  4.05             81
52       Olivia     Ph.dStewart       sk  3.95             80
53          Ava     Ph.dSanchez       yt  3.85             79
54     Isabella       Ph.dTomas       ab  3.75             78
55       Sophia       Ph.dDavid       bc  3.65             77
56    Charlotte        Ph.dReed       mb  3.55             76
57          Mia        Ph.dCook       nb  3.45             75
58       Amelia      Ph.dMorgan       nl  3.35             74
59       Harper        Ph.dBell       nt  3.25             73
60       Evelyn      Ph.dMurphy       ns  3.15             72
61      Abigail      Ph.dBailey       nu  3.05             71
62        Emily      Ph.dRivera       on  2.95             70
63    Elizabeth      Ph.dCooper       pe  2.85            100
64         Mila  Ph.dRichardson       qc  4.33             99
65         Ella         Ph.dCox       sk  4.20             98
66        Avery      Ph.dHoward       yt  4.10             97
67        Sofia        Ph.dWard       ab  4.00             96
68       Camila      Ph.dTorres       bc  3.90             95
69         Aria    Ph.dPeterson       mb  3.80             94
70     Scarlett        Ph.dGray       nb  3.70             93
71     Victoria     Ph.dRamirez       nl  3.60             92
72      Madison       Ph.dJames       nt  3.50             91
73         Luna      Ph.dWatson       ns  3.40             90
74        Grace      Ph.dBrooks       nu  3.30             89
75        Chloe       Ph.dKelly       on  3.20             88
76     Penelope     Ph.dSanders       pe  3.10             87
77        Layla       Ph.dPrice       qc  3.00             86
78        Riley     Ph.dBennett       sk  2.90             85
79         Zoey        Ph.dWood       yt  2.80             84
80         Nora      Ph.dBarnes       ab  4.25             83
81         Lily        Ph.dRoss       bc  4.15             82
82      Eleanor   Ph.dHenderson       mb  4.05             81
83       Hannah     Ph.dColeman       nb  3.95             80
84      Lillian     Ph.dJenkins       nl  3.85             79
85      Addison       Ph.dPerry       nt  3.75             78
86       Aubrey      Ph.dPowell       ns  3.65             77
87        Ellie        Ph.dLong       nu  3.55             76
88       Stella   Ph.dPatterson       on  3.45             75
89      Natalie      Ph.dHughes       pe  3.35             74
90          Zoe      Ph.dFlores       qc  3.25             73
91         Leah  Ph.dWashington       sk  3.15             72
92        Hazel      Ph.dButler       yt  3.05             71
93       Violet     Ph.dSimmons       ab  2.95             70
94       Aurora      Ph.dFoster       bc  2.85            100
95     Savannah    Ph.dGonzales       mb  3.85             99
96       Audrey      Ph.dBryant       nb  3.75             98
97     Brooklyn   Ph.dAlexander       nl  3.65             97
98        Bella     Ph.dRussell       nt  3.55             96
99       Claire     Ph.dGriffin       ns  3.45             95

In [5]:
df2=pd.read_csv("international-stu.txt", sep=",")
df2

,FirstName,LastName,Country,CGPA,ResearchScore,Reading,Listening,Speaking,Writing
0,Alex,Zhang,China,3.70,95,24,25,29,26
1,Peter,Choi,Korea,4.00,85,23,19,22,28
2,Chaewon,Kim,Korea,3.10,82,22,22,23,27
3,Daeun,Gim,Korea,3.00,83,21,21,24,26
4,Eungyung,Ghim,Korea,2.90,84,20,20,25,25
5,Eunji,Lee,Korea,2.80,85,25,26,26,24
6,Eunjoo,Yi,Korea,4.25,86,25,25,27,23
7,Eunjung,Rhee,Korea,4.15,87,26,26,19,22
8,Eunsuh,Yie,Korea,4.05,88,27,27,29,21
9,Eunyoung,Park,Korea,3.95,89,28,28,30,20
10,Gyunghui,Pak,Korea,3.85,90,29,29,29,19
11,Gyungmi,Bahk,Korea,3.75,91,30,30,28,29
12,Haeun,Choi,Korea,3.65,92,24,25,29,30
13,Hayoon,Choe,Korea,3.55,93,23,19,22,26
14,Heejin,Jung,Korea,3.45,94,22,22,23,28
15,Heeyoung,Jeong,Korea,3.35,95,21,21,24,27
16,Hyejin,Chung,Korea,3.25,96,20,20,25,26
17,Hyunjoo,Cheong,Korea,3.30,89,25,26,26,25
18,Mingmei,Wang,China,3.15,97,25,25,27,24
19,Quan,Zhang,China,3.05,98,26,26,19,23
20,Shufang,Li,China,2.95,99,27,27,29,22
21,Ting,Fang,China,2.85,100,28,28,30,21
22,Tingting,Zhao,China,4.33,99,29,29,29,20
23,Jieming,Qian,China,4.20,98,30,30,28,19
24,Fanghua,Sun,China,4.10,97,24,25,29,26
25,Zhengqiu,Zhou,China,4.00,96,23,19,22,28
26,Xiaoying,Wu,China,3.90,95,22,22,23,27
27,Xiaomei,Zheng,China,3.80,94,21,21,24,26
28,Bingyu,Qi,China,3.70,93,20,20,25,25
29,Haibo,Liu,China,3.60,92,25,26,26,24
30,Rong,Cheng,China,3.50,91,25,25,27,23
31,Zhaoguo,Yang,China,3.40,90,26,26,19,22
32,Byungchul,Kim,Korea,3.20,88,27,27,29,21
33,Daehyun,Gim,Korea,3.10,87,28,28,30,20
34,Dohyun,Ghim,Korea,3.00,86,29,29,29,19
35,Donghae,Lee,Korea,2.90,85,30,30,28,29
36,Donghyun,Yi,Korea,2.80,84,24,25,29,30
37,Dongwon,Rhee,Korea,4.25,83,23,19,22,26
38,Doyoon,Yie,Korea,4.15,82,22,22,23,28
39,Gunwoo,Park,Korea,4.05,81,21,21,24,27
40,Gyungho,Pak,Korea,3.95,80,20,20,25,26
41,Hajoon,Bahk,Korea,3.85,79,25,26,26,25
42,Hyunjoon,Choi,Korea,3.75,78,25,25,27,24
43,Hyunwoo,Choe,Korea,3.65,77,26,26,19,23
44,Jaehyun,Jung,Korea,3.55,76,27,27,29,22
45,Jaeyoung,Jeong,Korea,3.45,75,28,28,30,21
46,Jiho,Chung,Korea,3.35,74,29,29,29,20
47,Jihoo,Cheong,Korea,3.25,73,30,30,28,19
48,Alireza,Daghestani,Iran,3.15,72,24,25,29,26
49,Shayan,Gharabaghi,Iran,3.05,71,23,19,22,28
50,Mohammad,Darbandi,Iran,2.95,70,22,22,23,27
51,Reza,Shirvani,Iran,2.85,100,21,21,24,26
52,Mahdi,Iravani,Iran,4.33,99,20,20,25,25
53,Ehsan,Nakhjevani,Iran,4.20,98,25,26,26,24
54,Mostafa,Lankarani,Iran,4.10,97,25,25,27,23
55,Mehdi,Hasan,Iran,4.00,96,26,26,19,22
56,Hamid,Javadi,Iran,3.90,95,27,27,29,21
57,Kamran,Houshian,Iran,3.80,94,28,28,30,20
58,Yaser,Mohsen,Iran,3.70,93,29,29,29,19
59,Arman,Shams,Iran,3.60,92,30,30,28,29
60,Hossein,Rostami,Iran,3.50,91,24,25,29,30
61,Sepideh,Ghorbani,Iran,3.40,90,23,19,22,26
62,Priya,Chandra,Idian,3.30,89,22,22,23,28
63,Tanya,Asan,Idian,3.20,88,21,21,24,27
64,Priyanka,Abbott,Idian,3.10,87,20,20,25,26
65,Divya,Ahuja,Idian,3.00,86,25,26,26,25
66,tanvi,Arora,Idian,2.90,85,25,25,27,24
67,Ishita,Dholia,Idian,2.80,84,26,26,19,23
68,Vani,Ahluwalia,Idian,4.25,83,27,27,29,22
69,Anjali,Anand,Idian,4.15,82,28,28,30,21
70,Rahul,Banerjee,Idian,4.05,81,29,29,29,20
71,Abhishek,Bhat/Butt,Idian,3.95,80,30,30,28,19
72,Aditya,Bhattathiri,Idian,3.85,79,24,25,29,26
73,Amit,Desai,Idian,3.75,78,23,19,22,28
74,Mahesh,Bandyopadhyay,Idian,3.65,77,22,22,23,27
75,ROHIT,Chattopadhyay,Idian,3.55,76,21,21,24,26
76,Yash,Chopra,Idian,3.45,75,20,20,25,25
77,Ankit,Chaturvedi,Idian,3.35,74,25,26,26,24
78,Sara,Daghestani,Iran,3.25,73,25,25,27,23
79,Mary,Gharabaghi,Iran,3.15,72,26,26,19,22
80,Negin,Darbandi,Iran,3.05,71,27,27,29,21
81,Layla,Shirvani,Iran,2.95,70,28,28,30,20
82,Faezeh,Iravani,Iran,2.85,100,29,29,29,19
83,Mino,Nakhjevani,Iran,3.85,99,30,30,28,29
84,Eli,Lankarani,Iran,3.75,98,24,25,29,30
85,Katy,Hasan,Iran,3.65,97,23,19,22,26
86,Sima,Javadi,Iran,3.55,96,22,22,23,28
87,Setayesh,Shams,Iran,3.45,95,21,21,24,27
88,An,Wang,China,4.00,85,20,20,25,26
89,Bing,Zhang,China,3.70,90,25,26,26,25
90,Chen,Li,China,4.33,70,25,25,27,24
91,Deshi,Zhao,China,4.10,72,26,26,19,23
92,Qingxia,Sun,China,3.90,74,27,27,29,22
93,Jin,Zhou,China,3.80,75,28,28,30,21
94,Jing,Wu,China,3.70,76,29,29,29,20
95,Jun,Zheng,China,3.60,77,30,30,28,19
96,Xiaoping,Qi,China,3.50,78,26,26,19,23
97,Xin,Liu,China,3.40,79,27,27,29,22
98,JingWei,Cheng,China,3.30,80,28,28,30,21
99,Guanyin,Yang,China,3.20,81,29,29,29,20

In [6]:
df2["Sum"] = df2["Reading"] + df2["Listening"] + df2["Speaking"] + df2["Writing"] 
df2

,FirstName,LastName,Country,CGPA,ResearchScore,Reading,Listening,Speaking,Writing,Sum
0,Alex,Zhang,China,3.70,95,24,25,29,26,104
1,Peter,Choi,Korea,4.00,85,23,19,22,28,92
2,Chaewon,Kim,Korea,3.10,82,22,22,23,27,94
3,Daeun,Gim,Korea,3.00,83,21,21,24,26,92
4,Eungyung,Ghim,Korea,2.90,84,20,20,25,25,90
5,Eunji,Lee,Korea,2.80,85,25,26,26,24,101
6,Eunjoo,Yi,Korea,4.25,86,25,25,27,23,100
7,Eunjung,Rhee,Korea,4.15,87,26,26,19,22,93
8,Eunsuh,Yie,Korea,4.05,88,27,27,29,21,104
9,Eunyoung,Park,Korea,3.95,89,28,28,30,20,106
10,Gyunghui,Pak,Korea,3.85,90,29,29,29,19,106
11,Gyungmi,Bahk,Korea,3.75,91,30,30,28,29,117
12,Haeun,Choi,Korea,3.65,92,24,25,29,30,108
13,Hayoon,Choe,Korea,3.55,93,23,19,22,26,90
14,Heejin,Jung,Korea,3.45,94,22,22,23,28,95
15,Heeyoung,Jeong,Korea,3.35,95,21,21,24,27,93
16,Hyejin,Chung,Korea,3.25,96,20,20,25,26,91
17,Hyunjoo,Cheong,Korea,3.30,89,25,26,26,25,102
18,Mingmei,Wang,China,3.15,97,25,25,27,24,101
19,Quan,Zhang,China,3.05,98,26,26,19,23,94
20,Shufang,Li,China,2.95,99,27,27,29,22,105
21,Ting,Fang,China,2.85,100,28,28,30,21,107
22,Tingting,Zhao,China,4.33,99,29,29,29,20,107
23,Jieming,Qian,China,4.20,98,30,30,28,19,107
24,Fanghua,Sun,China,4.10,97,24,25,29,26,104
25,Zhengqiu,Zhou,China,4.00,96,23,19,22,28,92
26,Xiaoying,Wu,China,3.90,95,22,22,23,27,94
27,Xiaomei,Zheng,China,3.80,94,21,21,24,26,92
28,Bingyu,Qi,China,3.70,93,20,20,25,25,90
29,Haibo,Liu,China,3.60,92,25,26,26,24,101
30,Rong,Cheng,China,3.50,91,25,25,27,23,100
31,Zhaoguo,Yang,China,3.40,90,26,26,19,22,93
32,Byungchul,Kim,Korea,3.20,88,27,27,29,21,104
33,Daehyun,Gim,Korea,3.10,87,28,28,30,20,106
34,Dohyun,Ghim,Korea,3.00,86,29,29,29,19,106
35,Donghae,Lee,Korea,2.90,85,30,30,28,29,117
36,Donghyun,Yi,Korea,2.80,84,24,25,29,30,108
37,Dongwon,Rhee,Korea,4.25,83,23,19,22,26,90
38,Doyoon,Yie,Korea,4.15,82,22,22,23,28,95
39,Gunwoo,Park,Korea,4.05,81,21,21,24,27,93
40,Gyungho,Pak,Korea,3.95,80,20,20,25,26,91
41,Hajoon,Bahk,Korea,3.85,79,25,26,26,25,102
42,Hyunjoon,Choi,Korea,3.75,78,25,25,27,24,101
43,Hyunwoo,Choe,Korea,3.65,77,26,26,19,23,94
44,Jaehyun,Jung,Korea,3.55,76,27,27,29,22,105
45,Jaeyoung,Jeong,Korea,3.45,75,28,28,30,21,107
46,Jiho,Chung,Korea,3.35,74,29,29,29,20,107
47,Jihoo,Cheong,Korea,3.25,73,30,30,28,19,107
48,Alireza,Daghestani,Iran,3.15,72,24,25,29,26,104
49,Shayan,Gharabaghi,Iran,3.05,71,23,19,22,28,92
50,Mohammad,Darbandi,Iran,2.95,70,22,22,23,27,94
51,Reza,Shirvani,Iran,2.85,100,21,21,24,26,92
52,Mahdi,Iravani,Iran,4.33,99,20,20,25,25,90
53,Ehsan,Nakhjevani,Iran,4.20,98,25,26,26,24,101
54,Mostafa,Lankarani,Iran,4.10,97,25,25,27,23,100
55,Mehdi,Hasan,Iran,4.00,96,26,26,19,22,93
56,Hamid,Javadi,Iran,3.90,95,27,27,29,21,104
57,Kamran,Houshian,Iran,3.80,94,28,28,30,20,106
58,Yaser,Mohsen,Iran,3.70,93,29,29,29,19,106
59,Arman,Shams,Iran,3.60,92,30,30,28,29,117
60,Hossein,Rostami,Iran,3.50,91,24,25,29,30,108
61,Sepideh,Ghorbani,Iran,3.40,90,23,19,22,26,90
62,Priya,Chandra,Idian,3.30,89,22,22,23,28,95
63,Tanya,Asan,Idian,3.20,88,21,21,24,27,93
64,Priyanka,Abbott,Idian,3.10,87,20,20,25,26,91
65,Divya,Ahuja,Idian,3.00,86,25,26,26,25,102
66,tanvi,Arora,Idian,2.90,85,25,25,27,24,101
67,Ishita,Dholia,Idian,2.80,84,26,26,19,23,94
68,Vani,Ahluwalia,Idian,4.25,83,27,27,29,22,105
69,Anjali,Anand,Idian,4.15,82,28,28,30,21,107
70,Rahul,Banerjee,Idian,4.05,81,29,29,29,20,107
71,Abhishek,Bhat/Butt,Idian,3.95,80,30,30,28,19,107
72,Aditya,Bhattathiri,Idian,3.85,79,24,25,29,26,104
73,Amit,Desai,Idian,3.75,78,23,19,22,28,92
74,Mahesh,Bandyopadhyay,Idian,3.65,77,22,22,23,27,94
75,ROHIT,Chattopadhyay,Idian,3.55,76,21,21,24,26,92
76,Yash,Chopra,Idian,3.45,75,20,20,25,25,90
77,Ankit,Chaturvedi,Idian,3.35,74,25,26,26,24,101
78,Sara,Daghestani,Iran,3.25,73,25,25,27,23,100
79,Mary,Gharabaghi,Iran,3.15,72,26,26,19,22,93
80,Negin,Darbandi,Iran,3.05,71,27,27,29,21,104
81,Layla,Shirvani,Iran,2.95,70,28,28,30,20,106
82,Faezeh,Iravani,Iran,2.85,100,29,29,29,19,106
83,Mino,Nakhjevani,Iran,3.85,99,30,30,28,29,117
84,Eli,Lankarani,Iran,3.75,98,24,25,29,30,108
85,Katy,Hasan,Iran,3.65,97,23,19,22,26,90
86,Sima,Javadi,Iran,3.55,96,22,22,23,28,95
87,Setayesh,Shams,Iran,3.45,95,21,21,24,27,93
88,An,Wang,China,4.00,85,20,20,25,26,91
89,Bing,Zhang,China,3.70,90,25,26,26,25,102
90,Chen,Li,China,4.33,70,25,25,27,24,101
91,Deshi,Zhao,China,4.10,72,26,26,19,23,94
92,Qingxia,Sun,China,3.90,74,27,27,29,22,105
93,Jin,Zhou,China,3.80,75,28,28,30,21,107
94,Jing,Wu,China,3.70,76,29,29,29,20,107
95,Jun,Zheng,China,3.60,77,30,30,28,19,107
96,Xiaoping,Qi,China,3.50,78,26,26,19,23,94
97,Xin,Liu,China,3.40,79,27,27,29,22,105
98,JingWei,Cheng,China,3.30,80,28,28,30,21,107
99,Guanyin,Yang,China,3.20,81,29,29,29,20,107

In [7]:
df["Result"] = "Fail"
df

      FirstName        LastName Province  CGPA  ResearchScore Result
0          Mary       Ph.dWhite       bc  4.00             85   Fail
1          Mike       Ph.dHwang       on  3.70             90   Fail
2          Liam     Ph.dEdwards       ab  4.33             70   Fail
3          Noah     Ph.dCollins       bc  4.20             71   Fail
4       William     Ph.dStewart       mb  4.10             72   Fail
5         James     Ph.dSanchez       nb  4.00             73   Fail
6        Oliver       Ph.dTomas       nl  3.90             74   Fail
7      Benjamin       Ph.dDavid       nt  3.80             75   Fail
8        Elijah        Ph.dReed       ns  3.70             76   Fail
9         Lucas        Ph.dCook       nu  3.60             77   Fail
10        Mason      Ph.dMorgan       on  3.50             78   Fail
11        Logan        Ph.dBell       pe  3.40             79   Fail
12    Alexander      Ph.dMurphy       qc  3.30             80   Fail
13        Ethan      Ph.dBailey       sk  3.20             81   Fail
14        Jacob      Ph.dRivera       yt  3.10             82   Fail
15      Michael      Ph.dCooper       ab  3.00             83   Fail
16       Daniel  Ph.dRichardson       bc  2.90             84   Fail
17        Henry         Ph.dCox       mb  2.80             85   Fail
18      Jackson      Ph.dHoward       nb  4.25             86   Fail
19    Sebastian        Ph.dWard       nl  4.15             87   Fail
20        Aiden      Ph.dTorres       nt  4.05             88   Fail
21      Matthew    Ph.dPeterson       ns  3.95             89   Fail
22       Samuel        Ph.dGray       nu  3.85             90   Fail
23        David     Ph.dRamirez       on  3.75             91   Fail
24       Joseph       Ph.dJames       pe  3.65             92   Fail
25       Carter      Ph.dWatson       qc  3.55             93   Fail
26         Owen      Ph.dBrooks       sk  3.45             94   Fail
27        Wyatt       Ph.dKelly       yt  3.35             95   Fail
28         John     Ph.dSanders       ab  3.25             96   Fail
29         Jack       Ph.dPrice       bc  3.15             97   Fail
30         Luke     Ph.dBennett       mb  3.05             98   Fail
31       Jayden        Ph.dWood       nb  2.95             99   Fail
32        Dylan      Ph.dBarnes       nl  2.85            100   Fail
33      Grayson        Ph.dRoss       nt  4.33             99   Fail
34         Levi   Ph.dHenderson       ns  4.20             98   Fail
35        Isaac     Ph.dColeman       nu  4.10             97   Fail
36      Gabriel     Ph.dJenkins       on  4.00             96   Fail
37       Julian       Ph.dPerry       pe  3.90             95   Fail
38        Mateo      Ph.dPowell       qc  3.80             94   Fail
39      Anthony        Ph.dLong       sk  3.70             93   Fail
40        Jaxon   Ph.dPatterson       yt  3.60             92   Fail
41      Lincoln      Ph.dHughes       ab  3.50             91   Fail
42       Joshua      Ph.dFlores       bc  3.40             90   Fail
43  Christopher  Ph.dWashington       mb  3.30             89   Fail
44       Andrew      Ph.dButler       nb  3.20             88   Fail
45     Theodore     Ph.dSimmons       nl  3.10             87   Fail
46        Caleb      Ph.dFoster       nt  3.00             86   Fail
47         Ryan    Ph.dGonzales       ns  2.90             85   Fail
48        Asher      Ph.dBryant       nu  2.80             84   Fail
49       Nathan   Ph.dAlexander       on  4.25             83   Fail
50       Thomas     Ph.dRussell       pe  4.15             82   Fail
51         Emma     Ph.dGriffin       qc  4.05             81   Fail
52       Olivia     Ph.dStewart       sk  3.95             80   Fail
53          Ava     Ph.dSanchez       yt  3.85             79   Fail
54     Isabella       Ph.dTomas       ab  3.75             78   Fail
55       Sophia       Ph.dDavid       bc  3.65             77   Fail
56    Charlotte        Ph.dReed       mb  3.55             76   Fail
57          Mia        Ph.dCook       nb  3.45             75   Fail
58       Amelia      Ph.dMorgan       nl  3.35             74   Fail
59       Harper        Ph.dBell       nt  3.25             73   Fail
60       Evelyn      Ph.dMurphy       ns  3.15             72   Fail
61      Abigail      Ph.dBailey       nu  3.05             71   Fail
62        Emily      Ph.dRivera       on  2.95             70   Fail
63    Elizabeth      Ph.dCooper       pe  2.85            100   Fail
64         Mila  Ph.dRichardson       qc  4.33             99   Fail
65         Ella         Ph.dCox       sk  4.20             98   Fail
66        Avery      Ph.dHoward       yt  4.10             97   Fail
67        Sofia        Ph.dWard       ab  4.00             96   Fail
68       Camila      Ph.dTorres       bc  3.90             95   Fail
69         Aria    Ph.dPeterson       mb  3.80             94   Fail
70     Scarlett        Ph.dGray       nb  3.70             93   Fail
71     Victoria     Ph.dRamirez       nl  3.60             92   Fail
72      Madison       Ph.dJames       nt  3.50             91   Fail
73         Luna      Ph.dWatson       ns  3.40             90   Fail
74        Grace      Ph.dBrooks       nu  3.30             89   Fail
75        Chloe       Ph.dKelly       on  3.20             88   Fail
76     Penelope     Ph.dSanders       pe  3.10             87   Fail
77        Layla       Ph.dPrice       qc  3.00             86   Fail
78        Riley     Ph.dBennett       sk  2.90             85   Fail
79         Zoey        Ph.dWood       yt  2.80             84   Fail
80         Nora      Ph.dBarnes       ab  4.25             83   Fail
81         Lily        Ph.dRoss       bc  4.15             82   Fail
82      Eleanor   Ph.dHenderson       mb  4.05             81   Fail
83       Hannah     Ph.dColeman       nb  3.95             80   Fail
84      Lillian     Ph.dJenkins       nl  3.85             79   Fail
85      Addison       Ph.dPerry       nt  3.75             78   Fail
86       Aubrey      Ph.dPowell       ns  3.65             77   Fail
87        Ellie        Ph.dLong       nu  3.55             76   Fail
88       Stella   Ph.dPatterson       on  3.45             75   Fail
89      Natalie      Ph.dHughes       pe  3.35             74   Fail
90          Zoe      Ph.dFlores       qc  3.25             73   Fail
91         Leah  Ph.dWashington       sk  3.15             72   Fail
92        Hazel      Ph.dButler       yt  3.05             71   Fail
93       Violet     Ph.dSimmons       ab  2.95             70   Fail
94       Aurora      Ph.dFoster       bc  2.85            100   Fail
95     Savannah    Ph.dGonzales       mb  3.85             99   Fail
96       Audrey      Ph.dBryant       nb  3.75             98   Fail
97     Brooklyn   Ph.dAlexander       nl  3.65             97   Fail
98        Bella     Ph.dRussell       nt  3.55             96   Fail
99       Claire     Ph.dGriffin       ns  3.45             95   Fail

In [8]:
df.loc[(df["CGPA"]>4.0) & (df["ResearchScore"]>80), "Result"]= "Pass"
df

      FirstName        LastName Province  CGPA  ResearchScore Result
0          Mary       Ph.dWhite       bc  4.00             85   Fail
1          Mike       Ph.dHwang       on  3.70             90   Fail
2          Liam     Ph.dEdwards       ab  4.33             70   Fail
3          Noah     Ph.dCollins       bc  4.20             71   Fail
4       William     Ph.dStewart       mb  4.10             72   Fail
5         James     Ph.dSanchez       nb  4.00             73   Fail
6        Oliver       Ph.dTomas       nl  3.90             74   Fail
7      Benjamin       Ph.dDavid       nt  3.80             75   Fail
8        Elijah        Ph.dReed       ns  3.70             76   Fail
9         Lucas        Ph.dCook       nu  3.60             77   Fail
10        Mason      Ph.dMorgan       on  3.50             78   Fail
11        Logan        Ph.dBell       pe  3.40             79   Fail
12    Alexander      Ph.dMurphy       qc  3.30             80   Fail
13        Ethan      Ph.dBailey       sk  3.20             81   Fail
14        Jacob      Ph.dRivera       yt  3.10             82   Fail
15      Michael      Ph.dCooper       ab  3.00             83   Fail
16       Daniel  Ph.dRichardson       bc  2.90             84   Fail
17        Henry         Ph.dCox       mb  2.80             85   Fail
18      Jackson      Ph.dHoward       nb  4.25             86   Pass
19    Sebastian        Ph.dWard       nl  4.15             87   Pass
20        Aiden      Ph.dTorres       nt  4.05             88   Pass
21      Matthew    Ph.dPeterson       ns  3.95             89   Fail
22       Samuel        Ph.dGray       nu  3.85             90   Fail
23        David     Ph.dRamirez       on  3.75             91   Fail
24       Joseph       Ph.dJames       pe  3.65             92   Fail
25       Carter      Ph.dWatson       qc  3.55             93   Fail
26         Owen      Ph.dBrooks       sk  3.45             94   Fail
27        Wyatt       Ph.dKelly       yt  3.35             95   Fail
28         John     Ph.dSanders       ab  3.25             96   Fail
29         Jack       Ph.dPrice       bc  3.15             97   Fail
30         Luke     Ph.dBennett       mb  3.05             98   Fail
31       Jayden        Ph.dWood       nb  2.95             99   Fail
32        Dylan      Ph.dBarnes       nl  2.85            100   Fail
33      Grayson        Ph.dRoss       nt  4.33             99   Pass
34         Levi   Ph.dHenderson       ns  4.20             98   Pass
35        Isaac     Ph.dColeman       nu  4.10             97   Pass
36      Gabriel     Ph.dJenkins       on  4.00             96   Fail
37       Julian       Ph.dPerry       pe  3.90             95   Fail
38        Mateo      Ph.dPowell       qc  3.80             94   Fail
39      Anthony        Ph.dLong       sk  3.70             93   Fail
40        Jaxon   Ph.dPatterson       yt  3.60             92   Fail
41      Lincoln      Ph.dHughes       ab  3.50             91   Fail
42       Joshua      Ph.dFlores       bc  3.40             90   Fail
43  Christopher  Ph.dWashington       mb  3.30             89   Fail
44       Andrew      Ph.dButler       nb  3.20             88   Fail
45     Theodore     Ph.dSimmons       nl  3.10             87   Fail
46        Caleb      Ph.dFoster       nt  3.00             86   Fail
47         Ryan    Ph.dGonzales       ns  2.90             85   Fail
48        Asher      Ph.dBryant       nu  2.80             84   Fail
49       Nathan   Ph.dAlexander       on  4.25             83   Pass
50       Thomas     Ph.dRussell       pe  4.15             82   Pass
51         Emma     Ph.dGriffin       qc  4.05             81   Pass
52       Olivia     Ph.dStewart       sk  3.95             80   Fail
53          Ava     Ph.dSanchez       yt  3.85             79   Fail
54     Isabella       Ph.dTomas       ab  3.75             78   Fail
55       Sophia       Ph.dDavid       bc  3.65             77   Fail
56    Charlotte        Ph.dReed       mb  3.55             76   Fail
57          Mia        Ph.dCook       nb  3.45             75   Fail
58       Amelia      Ph.dMorgan       nl  3.35             74   Fail
59       Harper        Ph.dBell       nt  3.25             73   Fail
60       Evelyn      Ph.dMurphy       ns  3.15             72   Fail
61      Abigail      Ph.dBailey       nu  3.05             71   Fail
62        Emily      Ph.dRivera       on  2.95             70   Fail
63    Elizabeth      Ph.dCooper       pe  2.85            100   Fail
64         Mila  Ph.dRichardson       qc  4.33             99   Pass
65         Ella         Ph.dCox       sk  4.20             98   Pass
66        Avery      Ph.dHoward       yt  4.10             97   Pass
67        Sofia        Ph.dWard       ab  4.00             96   Fail
68       Camila      Ph.dTorres       bc  3.90             95   Fail
69         Aria    Ph.dPeterson       mb  3.80             94   Fail
70     Scarlett        Ph.dGray       nb  3.70             93   Fail
71     Victoria     Ph.dRamirez       nl  3.60             92   Fail
72      Madison       Ph.dJames       nt  3.50             91   Fail
73         Luna      Ph.dWatson       ns  3.40             90   Fail
74        Grace      Ph.dBrooks       nu  3.30             89   Fail
75        Chloe       Ph.dKelly       on  3.20             88   Fail
76     Penelope     Ph.dSanders       pe  3.10             87   Fail
77        Layla       Ph.dPrice       qc  3.00             86   Fail
78        Riley     Ph.dBennett       sk  2.90             85   Fail
79         Zoey        Ph.dWood       yt  2.80             84   Fail
80         Nora      Ph.dBarnes       ab  4.25             83   Pass
81         Lily        Ph.dRoss       bc  4.15             82   Pass
82      Eleanor   Ph.dHenderson       mb  4.05             81   Pass
83       Hannah     Ph.dColeman       nb  3.95             80   Fail
84      Lillian     Ph.dJenkins       nl  3.85             79   Fail
85      Addison       Ph.dPerry       nt  3.75             78   Fail
86       Aubrey      Ph.dPowell       ns  3.65             77   Fail
87        Ellie        Ph.dLong       nu  3.55             76   Fail
88       Stella   Ph.dPatterson       on  3.45             75   Fail
89      Natalie      Ph.dHughes       pe  3.35             74   Fail
90          Zoe      Ph.dFlores       qc  3.25             73   Fail
91         Leah  Ph.dWashington       sk  3.15             72   Fail
92        Hazel      Ph.dButler       yt  3.05             71   Fail
93       Violet     Ph.dSimmons       ab  2.95             70   Fail
94       Aurora      Ph.dFoster       bc  2.85            100   Fail
95     Savannah    Ph.dGonzales       mb  3.85             99   Fail
96       Audrey      Ph.dBryant       nb  3.75             98   Fail
97     Brooklyn   Ph.dAlexander       nl  3.65             97   Fail
98        Bella     Ph.dRussell       nt  3.55             96   Fail
99       Claire     Ph.dGriffin       ns  3.45             95   Fail

In [9]:
df.drop(columns="LastName",inplace=True)
df

      FirstName Province  CGPA  ResearchScore Result
0          Mary       bc  4.00             85   Fail
1          Mike       on  3.70             90   Fail
2          Liam       ab  4.33             70   Fail
3          Noah       bc  4.20             71   Fail
4       William       mb  4.10             72   Fail
5         James       nb  4.00             73   Fail
6        Oliver       nl  3.90             74   Fail
7      Benjamin       nt  3.80             75   Fail
8        Elijah       ns  3.70             76   Fail
9         Lucas       nu  3.60             77   Fail
10        Mason       on  3.50             78   Fail
11        Logan       pe  3.40             79   Fail
12    Alexander       qc  3.30             80   Fail
13        Ethan       sk  3.20             81   Fail
14        Jacob       yt  3.10             82   Fail
15      Michael       ab  3.00             83   Fail
16       Daniel       bc  2.90             84   Fail
17        Henry       mb  2.80             85   Fail
18      Jackson       nb  4.25             86   Pass
19    Sebastian       nl  4.15             87   Pass
20        Aiden       nt  4.05             88   Pass
21      Matthew       ns  3.95             89   Fail
22       Samuel       nu  3.85             90   Fail
23        David       on  3.75             91   Fail
24       Joseph       pe  3.65             92   Fail
25       Carter       qc  3.55             93   Fail
26         Owen       sk  3.45             94   Fail
27        Wyatt       yt  3.35             95   Fail
28         John       ab  3.25             96   Fail
29         Jack       bc  3.15             97   Fail
30         Luke       mb  3.05             98   Fail
31       Jayden       nb  2.95             99   Fail
32        Dylan       nl  2.85            100   Fail
33      Grayson       nt  4.33             99   Pass
34         Levi       ns  4.20             98   Pass
35        Isaac       nu  4.10             97   Pass
36      Gabriel       on  4.00             96   Fail
37       Julian       pe  3.90             95   Fail
38        Mateo       qc  3.80             94   Fail
39      Anthony       sk  3.70             93   Fail
40        Jaxon       yt  3.60             92   Fail
41      Lincoln       ab  3.50             91   Fail
42       Joshua       bc  3.40             90   Fail
43  Christopher       mb  3.30             89   Fail
44       Andrew       nb  3.20             88   Fail
45     Theodore       nl  3.10             87   Fail
46        Caleb       nt  3.00             86   Fail
47         Ryan       ns  2.90             85   Fail
48        Asher       nu  2.80             84   Fail
49       Nathan       on  4.25             83   Pass
50       Thomas       pe  4.15             82   Pass
51         Emma       qc  4.05             81   Pass
52       Olivia       sk  3.95             80   Fail
53          Ava       yt  3.85             79   Fail
54     Isabella       ab  3.75             78   Fail
55       Sophia       bc  3.65             77   Fail
56    Charlotte       mb  3.55             76   Fail
57          Mia       nb  3.45             75   Fail
58       Amelia       nl  3.35             74   Fail
59       Harper       nt  3.25             73   Fail
60       Evelyn       ns  3.15             72   Fail
61      Abigail       nu  3.05             71   Fail
62        Emily       on  2.95             70   Fail
63    Elizabeth       pe  2.85            100   Fail
64         Mila       qc  4.33             99   Pass
65         Ella       sk  4.20             98   Pass
66        Avery       yt  4.10             97   Pass
67        Sofia       ab  4.00             96   Fail
68       Camila       bc  3.90             95   Fail
69         Aria       mb  3.80             94   Fail
70     Scarlett       nb  3.70             93   Fail
71     Victoria       nl  3.60             92   Fail
72      Madison       nt  3.50             91   Fail
73         Luna       ns  3.40             90   Fail
74        Grace       nu  3.30             89   Fail
75        Chloe       on  3.20             88   Fail
76     Penelope       pe  3.10             87   Fail
77        Layla       qc  3.00             86   Fail
78        Riley       sk  2.90             85   Fail
79         Zoey       yt  2.80             84   Fail
80         Nora       ab  4.25             83   Pass
81         Lily       bc  4.15             82   Pass
82      Eleanor       mb  4.05             81   Pass
83       Hannah       nb  3.95             80   Fail
84      Lillian       nl  3.85             79   Fail
85      Addison       nt  3.75             78   Fail
86       Aubrey       ns  3.65             77   Fail
87        Ellie       nu  3.55             76   Fail
88       Stella       on  3.45             75   Fail
89      Natalie       pe  3.35             74   Fail
90          Zoe       qc  3.25             73   Fail
91         Leah       sk  3.15             72   Fail
92        Hazel       yt  3.05             71   Fail
93       Violet       ab  2.95             70   Fail
94       Aurora       bc  2.85            100   Fail
95     Savannah       mb  3.85             99   Fail
96       Audrey       nb  3.75             98   Fail
97     Brooklyn       nl  3.65             97   Fail
98        Bella       nt  3.55             96   Fail
99       Claire       ns  3.45             95   Fail

In [10]:
df

      FirstName Province  CGPA  ResearchScore Result
0          Mary       bc  4.00             85   Fail
1          Mike       on  3.70             90   Fail
2          Liam       ab  4.33             70   Fail
3          Noah       bc  4.20             71   Fail
4       William       mb  4.10             72   Fail
5         James       nb  4.00             73   Fail
6        Oliver       nl  3.90             74   Fail
7      Benjamin       nt  3.80             75   Fail
8        Elijah       ns  3.70             76   Fail
9         Lucas       nu  3.60             77   Fail
10        Mason       on  3.50             78   Fail
11        Logan       pe  3.40             79   Fail
12    Alexander       qc  3.30             80   Fail
13        Ethan       sk  3.20             81   Fail
14        Jacob       yt  3.10             82   Fail
15      Michael       ab  3.00             83   Fail
16       Daniel       bc  2.90             84   Fail
17        Henry       mb  2.80             85   Fail
18      Jackson       nb  4.25             86   Pass
19    Sebastian       nl  4.15             87   Pass
20        Aiden       nt  4.05             88   Pass
21      Matthew       ns  3.95             89   Fail
22       Samuel       nu  3.85             90   Fail
23        David       on  3.75             91   Fail
24       Joseph       pe  3.65             92   Fail
25       Carter       qc  3.55             93   Fail
26         Owen       sk  3.45             94   Fail
27        Wyatt       yt  3.35             95   Fail
28         John       ab  3.25             96   Fail
29         Jack       bc  3.15             97   Fail
30         Luke       mb  3.05             98   Fail
31       Jayden       nb  2.95             99   Fail
32        Dylan       nl  2.85            100   Fail
33      Grayson       nt  4.33             99   Pass
34         Levi       ns  4.20             98   Pass
35        Isaac       nu  4.10             97   Pass
36      Gabriel       on  4.00             96   Fail
37       Julian       pe  3.90             95   Fail
38        Mateo       qc  3.80             94   Fail
39      Anthony       sk  3.70             93   Fail
40        Jaxon       yt  3.60             92   Fail
41      Lincoln       ab  3.50             91   Fail
42       Joshua       bc  3.40             90   Fail
43  Christopher       mb  3.30             89   Fail
44       Andrew       nb  3.20             88   Fail
45     Theodore       nl  3.10             87   Fail
46        Caleb       nt  3.00             86   Fail
47         Ryan       ns  2.90             85   Fail
48        Asher       nu  2.80             84   Fail
49       Nathan       on  4.25             83   Pass
50       Thomas       pe  4.15             82   Pass
51         Emma       qc  4.05             81   Pass
52       Olivia       sk  3.95             80   Fail
53          Ava       yt  3.85             79   Fail
54     Isabella       ab  3.75             78   Fail
55       Sophia       bc  3.65             77   Fail
56    Charlotte       mb  3.55             76   Fail
57          Mia       nb  3.45             75   Fail
58       Amelia       nl  3.35             74   Fail
59       Harper       nt  3.25             73   Fail
60       Evelyn       ns  3.15             72   Fail
61      Abigail       nu  3.05             71   Fail
62        Emily       on  2.95             70   Fail
63    Elizabeth       pe  2.85            100   Fail
64         Mila       qc  4.33             99   Pass
65         Ella       sk  4.20             98   Pass
66        Avery       yt  4.10             97   Pass
67        Sofia       ab  4.00             96   Fail
68       Camila       bc  3.90             95   Fail
69         Aria       mb  3.80             94   Fail
70     Scarlett       nb  3.70             93   Fail
71     Victoria       nl  3.60             92   Fail
72      Madison       nt  3.50             91   Fail
73         Luna       ns  3.40             90   Fail
74        Grace       nu  3.30             89   Fail
75        Chloe       on  3.20             88   Fail
76     Penelope       pe  3.10             87   Fail
77        Layla       qc  3.00             86   Fail
78        Riley       sk  2.90             85   Fail
79         Zoey       yt  2.80             84   Fail
80         Nora       ab  4.25             83   Pass
81         Lily       bc  4.15             82   Pass
82      Eleanor       mb  4.05             81   Pass
83       Hannah       nb  3.95             80   Fail
84      Lillian       nl  3.85             79   Fail
85      Addison       nt  3.75             78   Fail
86       Aubrey       ns  3.65             77   Fail
87        Ellie       nu  3.55             76   Fail
88       Stella       on  3.45             75   Fail
89      Natalie       pe  3.35             74   Fail
90          Zoe       qc  3.25             73   Fail
91         Leah       sk  3.15             72   Fail
92        Hazel       yt  3.05             71   Fail
93       Violet       ab  2.95             70   Fail
94       Aurora       bc  2.85            100   Fail
95     Savannah       mb  3.85             99   Fail
96       Audrey       nb  3.75             98   Fail
97     Brooklyn       nl  3.65             97   Fail
98        Bella       nt  3.55             96   Fail
99       Claire       ns  3.45             95   Fail

In [11]:
df.drop(index = 6)

      FirstName Province  CGPA  ResearchScore Result
0          Mary       bc  4.00             85   Fail
1          Mike       on  3.70             90   Fail
2          Liam       ab  4.33             70   Fail
3          Noah       bc  4.20             71   Fail
4       William       mb  4.10             72   Fail
5         James       nb  4.00             73   Fail
7      Benjamin       nt  3.80             75   Fail
8        Elijah       ns  3.70             76   Fail
9         Lucas       nu  3.60             77   Fail
10        Mason       on  3.50             78   Fail
11        Logan       pe  3.40             79   Fail
12    Alexander       qc  3.30             80   Fail
13        Ethan       sk  3.20             81   Fail
14        Jacob       yt  3.10             82   Fail
15      Michael       ab  3.00             83   Fail
16       Daniel       bc  2.90             84   Fail
17        Henry       mb  2.80             85   Fail
18      Jackson       nb  4.25             86   Pass
19    Sebastian       nl  4.15             87   Pass
20        Aiden       nt  4.05             88   Pass
21      Matthew       ns  3.95             89   Fail
22       Samuel       nu  3.85             90   Fail
23        David       on  3.75             91   Fail
24       Joseph       pe  3.65             92   Fail
25       Carter       qc  3.55             93   Fail
26         Owen       sk  3.45             94   Fail
27        Wyatt       yt  3.35             95   Fail
28         John       ab  3.25             96   Fail
29         Jack       bc  3.15             97   Fail
30         Luke       mb  3.05             98   Fail
31       Jayden       nb  2.95             99   Fail
32        Dylan       nl  2.85            100   Fail
33      Grayson       nt  4.33             99   Pass
34         Levi       ns  4.20             98   Pass
35        Isaac       nu  4.10             97   Pass
36      Gabriel       on  4.00             96   Fail
37       Julian       pe  3.90             95   Fail
38        Mateo       qc  3.80             94   Fail
39      Anthony       sk  3.70             93   Fail
40        Jaxon       yt  3.60             92   Fail
41      Lincoln       ab  3.50             91   Fail
42       Joshua       bc  3.40             90   Fail
43  Christopher       mb  3.30             89   Fail
44       Andrew       nb  3.20             88   Fail
45     Theodore       nl  3.10             87   Fail
46        Caleb       nt  3.00             86   Fail
47         Ryan       ns  2.90             85   Fail
48        Asher       nu  2.80             84   Fail
49       Nathan       on  4.25             83   Pass
50       Thomas       pe  4.15             82   Pass
51         Emma       qc  4.05             81   Pass
52       Olivia       sk  3.95             80   Fail
53          Ava       yt  3.85             79   Fail
54     Isabella       ab  3.75             78   Fail
55       Sophia       bc  3.65             77   Fail
56    Charlotte       mb  3.55             76   Fail
57          Mia       nb  3.45             75   Fail
58       Amelia       nl  3.35             74   Fail
59       Harper       nt  3.25             73   Fail
60       Evelyn       ns  3.15             72   Fail
61      Abigail       nu  3.05             71   Fail
62        Emily       on  2.95             70   Fail
63    Elizabeth       pe  2.85            100   Fail
64         Mila       qc  4.33             99   Pass
65         Ella       sk  4.20             98   Pass
66        Avery       yt  4.10             97   Pass
67        Sofia       ab  4.00             96   Fail
68       Camila       bc  3.90             95   Fail
69         Aria       mb  3.80             94   Fail
70     Scarlett       nb  3.70             93   Fail
71     Victoria       nl  3.60             92   Fail
72      Madison       nt  3.50             91   Fail
73         Luna       ns  3.40             90   Fail
74        Grace       nu  3.30             89   Fail
75        Chloe       on  3.20             88   Fail
76     Penelope       pe  3.10             87   Fail
77        Layla       qc  3.00             86   Fail
78        Riley       sk  2.90             85   Fail
79         Zoey       yt  2.80             84   Fail
80         Nora       ab  4.25             83   Pass
81         Lily       bc  4.15             82   Pass
82      Eleanor       mb  4.05             81   Pass
83       Hannah       nb  3.95             80   Fail
84      Lillian       nl  3.85             79   Fail
85      Addison       nt  3.75             78   Fail
86       Aubrey       ns  3.65             77   Fail
87        Ellie       nu  3.55             76   Fail
88       Stella       on  3.45             75   Fail
89      Natalie       pe  3.35             74   Fail
90          Zoe       qc  3.25             73   Fail
91         Leah       sk  3.15             72   Fail
92        Hazel       yt  3.05             71   Fail
93       Violet       ab  2.95             70   Fail
94       Aurora       bc  2.85            100   Fail
95     Savannah       mb  3.85             99   Fail
96       Audrey       nb  3.75             98   Fail
97     Brooklyn       nl  3.65             97   Fail
98        Bella       nt  3.55             96   Fail
99       Claire       ns  3.45             95   Fail

In [12]:
filter = df["CGPA"] < 3.5
df.drop(index = df[filter].index)

    FirstName Province  CGPA  ResearchScore Result
0        Mary       bc  4.00             85   Fail
1        Mike       on  3.70             90   Fail
2        Liam       ab  4.33             70   Fail
3        Noah       bc  4.20             71   Fail
4     William       mb  4.10             72   Fail
5       James       nb  4.00             73   Fail
6      Oliver       nl  3.90             74   Fail
7    Benjamin       nt  3.80             75   Fail
8      Elijah       ns  3.70             76   Fail
9       Lucas       nu  3.60             77   Fail
10      Mason       on  3.50             78   Fail
18    Jackson       nb  4.25             86   Pass
19  Sebastian       nl  4.15             87   Pass
20      Aiden       nt  4.05             88   Pass
21    Matthew       ns  3.95             89   Fail
22     Samuel       nu  3.85             90   Fail
23      David       on  3.75             91   Fail
24     Joseph       pe  3.65             92   Fail
25     Carter       qc  3.55             93   Fail
33    Grayson       nt  4.33             99   Pass
34       Levi       ns  4.20             98   Pass
35      Isaac       nu  4.10             97   Pass
36    Gabriel       on  4.00             96   Fail
37     Julian       pe  3.90             95   Fail
38      Mateo       qc  3.80             94   Fail
39    Anthony       sk  3.70             93   Fail
40      Jaxon       yt  3.60             92   Fail
41    Lincoln       ab  3.50             91   Fail
49     Nathan       on  4.25             83   Pass
50     Thomas       pe  4.15             82   Pass
51       Emma       qc  4.05             81   Pass
52     Olivia       sk  3.95             80   Fail
53        Ava       yt  3.85             79   Fail
54   Isabella       ab  3.75             78   Fail
55     Sophia       bc  3.65             77   Fail
56  Charlotte       mb  3.55             76   Fail
64       Mila       qc  4.33             99   Pass
65       Ella       sk  4.20             98   Pass
66      Avery       yt  4.10             97   Pass
67      Sofia       ab  4.00             96   Fail
68     Camila       bc  3.90             95   Fail
69       Aria       mb  3.80             94   Fail
70   Scarlett       nb  3.70             93   Fail
71   Victoria       nl  3.60             92   Fail
72    Madison       nt  3.50             91   Fail
80       Nora       ab  4.25             83   Pass
81       Lily       bc  4.15             82   Pass
82    Eleanor       mb  4.05             81   Pass
83     Hannah       nb  3.95             80   Fail
84    Lillian       nl  3.85             79   Fail
85    Addison       nt  3.75             78   Fail
86     Aubrey       ns  3.65             77   Fail
87      Ellie       nu  3.55             76   Fail
95   Savannah       mb  3.85             99   Fail
96     Audrey       nb  3.75             98   Fail
97   Brooklyn       nl  3.65             97   Fail
98      Bella       nt  3.55             96   Fail

In [13]:
df.loc[100] = ["KIM", "VC", 3.8, 90,"Fail"]
df

       FirstName Province  CGPA  ResearchScore Result
0           Mary       bc  4.00             85   Fail
1           Mike       on  3.70             90   Fail
2           Liam       ab  4.33             70   Fail
3           Noah       bc  4.20             71   Fail
4        William       mb  4.10             72   Fail
5          James       nb  4.00             73   Fail
6         Oliver       nl  3.90             74   Fail
7       Benjamin       nt  3.80             75   Fail
8         Elijah       ns  3.70             76   Fail
9          Lucas       nu  3.60             77   Fail
10         Mason       on  3.50             78   Fail
11         Logan       pe  3.40             79   Fail
12     Alexander       qc  3.30             80   Fail
13         Ethan       sk  3.20             81   Fail
14         Jacob       yt  3.10             82   Fail
15       Michael       ab  3.00             83   Fail
16        Daniel       bc  2.90             84   Fail
17         Henry       mb  2.80             85   Fail
18       Jackson       nb  4.25             86   Pass
19     Sebastian       nl  4.15             87   Pass
20         Aiden       nt  4.05             88   Pass
21       Matthew       ns  3.95             89   Fail
22        Samuel       nu  3.85             90   Fail
23         David       on  3.75             91   Fail
24        Joseph       pe  3.65             92   Fail
25        Carter       qc  3.55             93   Fail
26          Owen       sk  3.45             94   Fail
27         Wyatt       yt  3.35             95   Fail
28          John       ab  3.25             96   Fail
29          Jack       bc  3.15             97   Fail
30          Luke       mb  3.05             98   Fail
31        Jayden       nb  2.95             99   Fail
32         Dylan       nl  2.85            100   Fail
33       Grayson       nt  4.33             99   Pass
34          Levi       ns  4.20             98   Pass
35         Isaac       nu  4.10             97   Pass
36       Gabriel       on  4.00             96   Fail
37        Julian       pe  3.90             95   Fail
38         Mateo       qc  3.80             94   Fail
39       Anthony       sk  3.70             93   Fail
40         Jaxon       yt  3.60             92   Fail
41       Lincoln       ab  3.50             91   Fail
42        Joshua       bc  3.40             90   Fail
43   Christopher       mb  3.30             89   Fail
44        Andrew       nb  3.20             88   Fail
45      Theodore       nl  3.10             87   Fail
46         Caleb       nt  3.00             86   Fail
47          Ryan       ns  2.90             85   Fail
48         Asher       nu  2.80             84   Fail
49        Nathan       on  4.25             83   Pass
50        Thomas       pe  4.15             82   Pass
51          Emma       qc  4.05             81   Pass
52        Olivia       sk  3.95             80   Fail
53           Ava       yt  3.85             79   Fail
54      Isabella       ab  3.75             78   Fail
55        Sophia       bc  3.65             77   Fail
56     Charlotte       mb  3.55             76   Fail
57           Mia       nb  3.45             75   Fail
58        Amelia       nl  3.35             74   Fail
59        Harper       nt  3.25             73   Fail
60        Evelyn       ns  3.15             72   Fail
61       Abigail       nu  3.05             71   Fail
62         Emily       on  2.95             70   Fail
63     Elizabeth       pe  2.85            100   Fail
64          Mila       qc  4.33             99   Pass
65          Ella       sk  4.20             98   Pass
66         Avery       yt  4.10             97   Pass
67         Sofia       ab  4.00             96   Fail
68        Camila       bc  3.90             95   Fail
69          Aria       mb  3.80             94   Fail
70      Scarlett       nb  3.70             93   Fail
71      Victoria       nl  3.60             92   Fail
72       Madison       nt  3.50             91   Fail
73          Luna       ns  3.40             90   Fail
74         Grace       nu  3.30             89   Fail
75         Chloe       on  3.20             88   Fail
76      Penelope       pe  3.10             87   Fail
77         Layla       qc  3.00             86   Fail
78         Riley       sk  2.90             85   Fail
79          Zoey       yt  2.80             84   Fail
80          Nora       ab  4.25             83   Pass
81          Lily       bc  4.15             82   Pass
82       Eleanor       mb  4.05             81   Pass
83        Hannah       nb  3.95             80   Fail
84       Lillian       nl  3.85             79   Fail
85       Addison       nt  3.75             78   Fail
86        Aubrey       ns  3.65             77   Fail
87         Ellie       nu  3.55             76   Fail
88        Stella       on  3.45             75   Fail
89       Natalie       pe  3.35             74   Fail
90           Zoe       qc  3.25             73   Fail
91          Leah       sk  3.15             72   Fail
92         Hazel       yt  3.05             71   Fail
93        Violet       ab  2.95             70   Fail
94        Aurora       bc  2.85            100   Fail
95      Savannah       mb  3.85             99   Fail
96        Audrey       nb  3.75             98   Fail
97      Brooklyn       nl  3.65             97   Fail
98         Bella       nt  3.55             96   Fail
99        Claire       ns  3.45             95   Fail
100          KIM       VC  3.80             90   Fail

In [15]:
df.loc["KIM","ResearchScore"]=87
df

       FirstName Province  CGPA  ResearchScore Result
0           Mary       bc  4.00           85.0   Fail
1           Mike       on  3.70           90.0   Fail
2           Liam       ab  4.33           70.0   Fail
3           Noah       bc  4.20           71.0   Fail
4        William       mb  4.10           72.0   Fail
5          James       nb  4.00           73.0   Fail
6         Oliver       nl  3.90           74.0   Fail
7       Benjamin       nt  3.80           75.0   Fail
8         Elijah       ns  3.70           76.0   Fail
9          Lucas       nu  3.60           77.0   Fail
10         Mason       on  3.50           78.0   Fail
11         Logan       pe  3.40           79.0   Fail
12     Alexander       qc  3.30           80.0   Fail
13         Ethan       sk  3.20           81.0   Fail
14         Jacob       yt  3.10           82.0   Fail
15       Michael       ab  3.00           83.0   Fail
16        Daniel       bc  2.90           84.0   Fail
17         Henry       mb  2.80           85.0   Fail
18       Jackson       nb  4.25           86.0   Pass
19     Sebastian       nl  4.15           87.0   Pass
20         Aiden       nt  4.05           88.0   Pass
21       Matthew       ns  3.95           89.0   Fail
22        Samuel       nu  3.85           90.0   Fail
23         David       on  3.75           91.0   Fail
24        Joseph       pe  3.65           92.0   Fail
25        Carter       qc  3.55           93.0   Fail
26          Owen       sk  3.45           94.0   Fail
27         Wyatt       yt  3.35           95.0   Fail
28          John       ab  3.25           96.0   Fail
29          Jack       bc  3.15           97.0   Fail
30          Luke       mb  3.05           98.0   Fail
31        Jayden       nb  2.95           99.0   Fail
32         Dylan       nl  2.85          100.0   Fail
33       Grayson       nt  4.33           99.0   Pass
34          Levi       ns  4.20           98.0   Pass
35         Isaac       nu  4.10           97.0   Pass
36       Gabriel       on  4.00           96.0   Fail
37        Julian       pe  3.90           95.0   Fail
38         Mateo       qc  3.80           94.0   Fail
39       Anthony       sk  3.70           93.0   Fail
40         Jaxon       yt  3.60           92.0   Fail
41       Lincoln       ab  3.50           91.0   Fail
42        Joshua       bc  3.40           90.0   Fail
43   Christopher       mb  3.30           89.0   Fail
44        Andrew       nb  3.20           88.0   Fail
45      Theodore       nl  3.10           87.0   Fail
46         Caleb       nt  3.00           86.0   Fail
47          Ryan       ns  2.90           85.0   Fail
48         Asher       nu  2.80           84.0   Fail
49        Nathan       on  4.25           83.0   Pass
50        Thomas       pe  4.15           82.0   Pass
51          Emma       qc  4.05           81.0   Pass
52        Olivia       sk  3.95           80.0   Fail
53           Ava       yt  3.85           79.0   Fail
54      Isabella       ab  3.75           78.0   Fail
55        Sophia       bc  3.65           77.0   Fail
56     Charlotte       mb  3.55           76.0   Fail
57           Mia       nb  3.45           75.0   Fail
58        Amelia       nl  3.35           74.0   Fail
59        Harper       nt  3.25           73.0   Fail
60        Evelyn       ns  3.15           72.0   Fail
61       Abigail       nu  3.05           71.0   Fail
62         Emily       on  2.95           70.0   Fail
63     Elizabeth       pe  2.85          100.0   Fail
64          Mila       qc  4.33           99.0   Pass
65          Ella       sk  4.20           98.0   Pass
66         Avery       yt  4.10           97.0   Pass
67         Sofia       ab  4.00           96.0   Fail
68        Camila       bc  3.90           95.0   Fail
69          Aria       mb  3.80           94.0   Fail
70      Scarlett       nb  3.70           93.0   Fail
71      Victoria       nl  3.60           92.0   Fail
72       Madison       nt  3.50           91.0   Fail
73          Luna       ns  3.40           90.0   Fail
74         Grace       nu  3.30           89.0   Fail
75         Chloe       on  3.20           88.0   Fail
76      Penelope       pe  3.10           87.0   Fail
77         Layla       qc  3.00           86.0   Fail
78         Riley       sk  2.90           85.0   Fail
79          Zoey       yt  2.80           84.0   Fail
80          Nora       ab  4.25           83.0   Pass
81          Lily       bc  4.15           82.0   Pass
82       Eleanor       mb  4.05           81.0   Pass
83        Hannah       nb  3.95           80.0   Fail
84       Lillian       nl  3.85           79.0   Fail
85       Addison       nt  3.75           78.0   Fail
86        Aubrey       ns  3.65           77.0   Fail
87         Ellie       nu  3.55           76.0   Fail
88        Stella       on  3.45           75.0   Fail
89       Natalie       pe  3.35           74.0   Fail
90           Zoe       qc  3.25           73.0   Fail
91          Leah       sk  3.15           72.0   Fail
92         Hazel       yt  3.05           71.0   Fail
93        Violet       ab  2.95           70.0   Fail
94        Aurora       bc  2.85          100.0   Fail
95      Savannah       mb  3.85           99.0   Fail
96        Audrey       nb  3.75           98.0   Fail
97      Brooklyn       nl  3.65           97.0   Fail
98         Bella       nt  3.55           96.0   Fail
99        Claire       ns  3.45           95.0   Fail
100          KIM       VC  3.80           90.0   Fail
KIM          NaN      NaN   NaN           87.0    NaN

In [18]:
df.loc[24,["Province","CGPA"]]=["VC", 4.2]
df

       FirstName Province  CGPA  ResearchScore Result
0           Mary       bc  4.00           85.0   Fail
1           Mike       on  3.70           90.0   Fail
2           Liam       ab  4.33           70.0   Fail
3           Noah       bc  4.20           71.0   Fail
4        William       mb  4.10           72.0   Fail
5          James       nb  4.00           73.0   Fail
6         Oliver       nl  3.90           74.0   Fail
7       Benjamin       nt  3.80           75.0   Fail
8         Elijah       ns  3.70           76.0   Fail
9          Lucas       nu  3.60           77.0   Fail
10         Mason       on  3.50           78.0   Fail
11         Logan       pe  3.40           79.0   Fail
12     Alexander       qc  3.30           80.0   Fail
13         Ethan       sk  3.20           81.0   Fail
14         Jacob       yt  3.10           82.0   Fail
15       Michael       ab  3.00           83.0   Fail
16        Daniel       bc  2.90           84.0   Fail
17         Henry       mb  2.80           85.0   Fail
18       Jackson       nb  4.25           86.0   Pass
19     Sebastian       nl  4.15           87.0   Pass
20         Aiden       nt  4.05           88.0   Pass
21       Matthew       ns  3.95           89.0   Fail
22        Samuel       nu  3.85           90.0   Fail
23         David       on  3.75           91.0   Fail
24        Joseph       VC  4.20           92.0   Fail
25        Carter       qc  3.55           93.0   Fail
26          Owen       sk  3.45           94.0   Fail
27         Wyatt       yt  3.35           95.0   Fail
28          John       ab  3.25           96.0   Fail
29          Jack       bc  3.15           97.0   Fail
30          Luke       mb  3.05           98.0   Fail
31        Jayden       nb  2.95           99.0   Fail
32         Dylan       nl  2.85          100.0   Fail
33       Grayson       nt  4.33           99.0   Pass
34          Levi       ns  4.20           98.0   Pass
35         Isaac       nu  4.10           97.0   Pass
36       Gabriel       on  4.00           96.0   Fail
37        Julian       pe  3.90           95.0   Fail
38         Mateo       qc  3.80           94.0   Fail
39       Anthony       sk  3.70           93.0   Fail
40         Jaxon       yt  3.60           92.0   Fail
41       Lincoln       ab  3.50           91.0   Fail
42        Joshua       bc  3.40           90.0   Fail
43   Christopher       mb  3.30           89.0   Fail
44        Andrew       nb  3.20           88.0   Fail
45      Theodore       nl  3.10           87.0   Fail
46         Caleb       nt  3.00           86.0   Fail
47          Ryan       ns  2.90           85.0   Fail
48         Asher       nu  2.80           84.0   Fail
49        Nathan       on  4.25           83.0   Pass
50        Thomas       pe  4.15           82.0   Pass
51          Emma       qc  4.05           81.0   Pass
52        Olivia       sk  3.95           80.0   Fail
53           Ava       yt  3.85           79.0   Fail
54      Isabella       ab  3.75           78.0   Fail
55        Sophia       bc  3.65           77.0   Fail
56     Charlotte       mb  3.55           76.0   Fail
57           Mia       nb  3.45           75.0   Fail
58        Amelia       nl  3.35           74.0   Fail
59        Harper       nt  3.25           73.0   Fail
60        Evelyn       ns  3.15           72.0   Fail
61       Abigail       nu  3.05           71.0   Fail
62         Emily       on  2.95           70.0   Fail
63     Elizabeth       pe  2.85          100.0   Fail
64          Mila       qc  4.33           99.0   Pass
65          Ella       sk  4.20           98.0   Pass
66         Avery       yt  4.10           97.0   Pass
67         Sofia       ab  4.00           96.0   Fail
68        Camila       bc  3.90           95.0   Fail
69          Aria       mb  3.80           94.0   Fail
70      Scarlett       nb  3.70           93.0   Fail
71      Victoria       nl  3.60           92.0   Fail
72       Madison       nt  3.50           91.0   Fail
73          Luna       ns  3.40           90.0   Fail
74         Grace       nu  3.30           89.0   Fail
75         Chloe       on  3.20           88.0   Fail
76      Penelope       pe  3.10           87.0   Fail
77         Layla       qc  3.00           86.0   Fail
78         Riley       sk  2.90           85.0   Fail
79          Zoey       yt  2.80           84.0   Fail
80          Nora       ab  4.25           83.0   Pass
81          Lily       bc  4.15           82.0   Pass
82       Eleanor       mb  4.05           81.0   Pass
83        Hannah       nb  3.95           80.0   Fail
84       Lillian       nl  3.85           79.0   Fail
85       Addison       nt  3.75           78.0   Fail
86        Aubrey       ns  3.65           77.0   Fail
87         Ellie       nu  3.55           76.0   Fail
88        Stella       on  3.45           75.0   Fail
89       Natalie       pe  3.35           74.0   Fail
90           Zoe       qc  3.25           73.0   Fail
91          Leah       sk  3.15           72.0   Fail
92         Hazel       yt  3.05           71.0   Fail
93        Violet       ab  2.95           70.0   Fail
94        Aurora       bc  2.85          100.0   Fail
95      Savannah       mb  3.85           99.0   Fail
96        Audrey       nb  3.75           98.0   Fail
97      Brooklyn       nl  3.65           97.0   Fail
98         Bella       nt  3.55           96.0   Fail
99        Claire       ns  3.45           95.0   Fail
100          KIM       VC  3.80           87.0   Fail

In [20]:
cols = list(df.columns)
cols

['FirstName', 'Province', 'CGPA', 'ResearchScore', 'Result']

In [22]:
df.columns = ["Name","Province,","CGPA","ResearchScore", "Result"]
df

            Name Province,  CGPA  ResearchScore Result
0           Mary        bc  4.00           85.0   Fail
1           Mike        on  3.70           90.0   Fail
2           Liam        ab  4.33           70.0   Fail
3           Noah        bc  4.20           71.0   Fail
4        William        mb  4.10           72.0   Fail
5          James        nb  4.00           73.0   Fail
6         Oliver        nl  3.90           74.0   Fail
7       Benjamin        nt  3.80           75.0   Fail
8         Elijah        ns  3.70           76.0   Fail
9          Lucas        nu  3.60           77.0   Fail
10         Mason        on  3.50           78.0   Fail
11         Logan        pe  3.40           79.0   Fail
12     Alexander        qc  3.30           80.0   Fail
13         Ethan        sk  3.20           81.0   Fail
14         Jacob        yt  3.10           82.0   Fail
15       Michael        ab  3.00           83.0   Fail
16        Daniel        bc  2.90           84.0   Fail
17         Henry        mb  2.80           85.0   Fail
18       Jackson        nb  4.25           86.0   Pass
19     Sebastian        nl  4.15           87.0   Pass
20         Aiden        nt  4.05           88.0   Pass
21       Matthew        ns  3.95           89.0   Fail
22        Samuel        nu  3.85           90.0   Fail
23         David        on  3.75           91.0   Fail
24        Joseph        VC  4.20           92.0   Fail
25        Carter        qc  3.55           93.0   Fail
26          Owen        sk  3.45           94.0   Fail
27         Wyatt        yt  3.35           95.0   Fail
28          John        ab  3.25           96.0   Fail
29          Jack        bc  3.15           97.0   Fail
30          Luke        mb  3.05           98.0   Fail
31        Jayden        nb  2.95           99.0   Fail
32         Dylan        nl  2.85          100.0   Fail
33       Grayson        nt  4.33           99.0   Pass
34          Levi        ns  4.20           98.0   Pass
35         Isaac        nu  4.10           97.0   Pass
36       Gabriel        on  4.00           96.0   Fail
37        Julian        pe  3.90           95.0   Fail
38         Mateo        qc  3.80           94.0   Fail
39       Anthony        sk  3.70           93.0   Fail
40         Jaxon        yt  3.60           92.0   Fail
41       Lincoln        ab  3.50           91.0   Fail
42        Joshua        bc  3.40           90.0   Fail
43   Christopher        mb  3.30           89.0   Fail
44        Andrew        nb  3.20           88.0   Fail
45      Theodore        nl  3.10           87.0   Fail
46         Caleb        nt  3.00           86.0   Fail
47          Ryan        ns  2.90           85.0   Fail
48         Asher        nu  2.80           84.0   Fail
49        Nathan        on  4.25           83.0   Pass
50        Thomas        pe  4.15           82.0   Pass
51          Emma        qc  4.05           81.0   Pass
52        Olivia        sk  3.95           80.0   Fail
53           Ava        yt  3.85           79.0   Fail
54      Isabella        ab  3.75           78.0   Fail
55        Sophia        bc  3.65           77.0   Fail
56     Charlotte        mb  3.55           76.0   Fail
57           Mia        nb  3.45           75.0   Fail
58        Amelia        nl  3.35           74.0   Fail
59        Harper        nt  3.25           73.0   Fail
60        Evelyn        ns  3.15           72.0   Fail
61       Abigail        nu  3.05           71.0   Fail
62         Emily        on  2.95           70.0   Fail
63     Elizabeth        pe  2.85          100.0   Fail
64          Mila        qc  4.33           99.0   Pass
65          Ella        sk  4.20           98.0   Pass
66         Avery        yt  4.10           97.0   Pass
67         Sofia        ab  4.00           96.0   Fail
68        Camila        bc  3.90           95.0   Fail
69          Aria        mb  3.80           94.0   Fail
70      Scarlett        nb  3.70           93.0   Fail
71      Victoria        nl  3.60           92.0   Fail
72       Madison        nt  3.50           91.0   Fail
73          Luna        ns  3.40           90.0   Fail
74         Grace        nu  3.30           89.0   Fail
75         Chloe        on  3.20           88.0   Fail
76      Penelope        pe  3.10           87.0   Fail
77         Layla        qc  3.00           86.0   Fail
78         Riley        sk  2.90           85.0   Fail
79          Zoey        yt  2.80           84.0   Fail
80          Nora        ab  4.25           83.0   Pass
81          Lily        bc  4.15           82.0   Pass
82       Eleanor        mb  4.05           81.0   Pass
83        Hannah        nb  3.95           80.0   Fail
84       Lillian        nl  3.85           79.0   Fail
85       Addison        nt  3.75           78.0   Fail
86        Aubrey        ns  3.65           77.0   Fail
87         Ellie        nu  3.55           76.0   Fail
88        Stella        on  3.45           75.0   Fail
89       Natalie        pe  3.35           74.0   Fail
90           Zoe        qc  3.25           73.0   Fail
91          Leah        sk  3.15           72.0   Fail
92         Hazel        yt  3.05           71.0   Fail
93        Violet        ab  2.95           70.0   Fail
94        Aurora        bc  2.85          100.0   Fail
95      Savannah        mb  3.85           99.0   Fail
96        Audrey        nb  3.75           98.0   Fail
97      Brooklyn        nl  3.65           97.0   Fail
98         Bella        nt  3.55           96.0   Fail
99        Claire        ns  3.45           95.0   Fail
100          KIM        VC  3.80           87.0   Fail